language: rust

cache:
  directories:
    - $HOME/.cargo

rust:
    - stable
    - nightly
    - beta

env:
  - RUSTFLAGS="-D warnings"

os:
    - linux
    - osx

script:
    - env
    - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then 
        rustup component add rustfmt;
        cargo fmt -- --check;
      fi
    - cargo test -- --nocapture
    - cargo doc
